################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
uGFX/3rdparty/fatfs-0.13/documents/res \
uGFX/3rdparty/fatfs-0.13/source \
uGFX/3rdparty/petitfs-0.03/src \
uGFX/3rdparty/tinygl-0.4-ugfx/BeOS \
uGFX/3rdparty/tinygl-0.4-ugfx/examples \
uGFX/3rdparty/tinygl-0.4-ugfx/src \
uGFX/boards/addons/gdisp \
uGFX/boards/base/ArduinoTinyScreen/gfx \
uGFX/boards/base/ArduinoTinyScreen \
uGFX/boards/base/Embest-STM32-DMSTF4BB/example_chibios_2.x \
uGFX/boards/base/Embest-STM32-DMSTF4BB/example_chibios_3.x \
uGFX/boards/base/FireBull-STM32F103-FB/chibios_board \
uGFX/boards/base/HY-MiniSTM32V/chibios_board \
uGFX/boards/base/Marlin/chibios_board \
uGFX/boards/base/Mikromedia-Plus-STM32-M4/ChibiOS_Board \
uGFX/boards/base/Mikromedia-STM32-M4-ILI9341/ChibiOS_Board \
uGFX/boards/base/Olimex-SAM7EX256-GE8/example \
uGFX/boards/base/Olimex-STM32-LCD/chibios_board \
uGFX/boards/base/RaspberryPi/FreeRTOS \
uGFX/boards/base/RaspberryPi \
uGFX/boards/base/STM32F429i-Discovery/chibios \
uGFX/boards/base/STM32F439i-Eval/CubeHal \
uGFX/boards/base/STM32F469i-Discovery/CubeHAL \
uGFX/boards/base/STM32F469i-Discovery \
uGFX/boards/base/STM32F746-Discovery \
uGFX/demos/3rdparty/bubbles \
uGFX/demos/3rdparty/notepad-2 \
uGFX/demos/applications/combo \
uGFX/demos/applications/mandelbrot \
uGFX/demos/applications/notepad \
uGFX/demos/benchmarks \
uGFX/demos/games/justget10 \
uGFX/demos/games/minesweeper \
uGFX/demos/games/tetris \
uGFX/demos/modules/gadc \
uGFX/demos/modules/gaudio/oscilloscope \
uGFX/demos/modules/gaudio/play-vs1053 \
uGFX/demos/modules/gaudio/play-wave \
uGFX/demos/modules/gdisp/arcsectors \
uGFX/demos/modules/gdisp/basics \
uGFX/demos/modules/gdisp/circles \
uGFX/demos/modules/gdisp/fonts \
uGFX/demos/modules/gdisp/fonts_cyrillic \
uGFX/demos/modules/gdisp/images \
uGFX/demos/modules/gdisp/images_animated \
uGFX/demos/modules/gdisp/images_palettes \
uGFX/demos/modules/gdisp/multiple_displays \
uGFX/demos/modules/gdisp/pixmap \
uGFX/demos/modules/gdisp/polygons \
uGFX/demos/modules/gdisp/streaming \
uGFX/demos/modules/gdisp/thickarcs \
uGFX/demos/modules/gfile/fatfs \
uGFX/demos/modules/ginput/keyboard \
uGFX/demos/modules/gos/threads \
uGFX/demos/modules/gos/threads_advanced \
uGFX/demos/modules/gtimer \
uGFX/demos/modules/gtrans/basic \
uGFX/demos/modules/gwin/basic \
uGFX/demos/modules/gwin/button \
uGFX/demos/modules/gwin/checkbox \
uGFX/demos/modules/gwin/console \
uGFX/demos/modules/gwin/container \
uGFX/demos/modules/gwin/container_nested \
uGFX/demos/modules/gwin/frame \
uGFX/demos/modules/gwin/gl3d-gears \
uGFX/demos/modules/gwin/gl3d-spin \
uGFX/demos/modules/gwin/graph \
uGFX/demos/modules/gwin/imagebox \
uGFX/demos/modules/gwin/keyboard \
uGFX/demos/modules/gwin/label \
uGFX/demos/modules/gwin/list \
uGFX/demos/modules/gwin/progressbar \
uGFX/demos/modules/gwin/radio \
uGFX/demos/modules/gwin/slider \
uGFX/demos/modules/gwin/tabset \
uGFX/demos/modules/gwin/textedit \
uGFX/demos/modules/gwin/textedit_virtual_keyboard \
uGFX/demos/modules/gwin/widgets \
uGFX/demos/tools/touch_calibration_grabber \
uGFX/demos/tools/touch_driver_test \
uGFX/demos/tools/touch_raw_readings \
uGFX/demos/tools/uGFXnetDisplay \
uGFX/drivers/gadc/AT91SAM7 \
uGFX/drivers/gaudio/Win32 \
uGFX/drivers/gaudio/gadc \
uGFX/drivers/gaudio/pwm \
uGFX/drivers/gaudio/vs1053 \
uGFX/drivers/gdisp/AlteraFramereader \
uGFX/drivers/gdisp/ED060SC4 \
uGFX/drivers/gdisp/Fb24bpp \
uGFX/drivers/gdisp/HX8347D \
uGFX/drivers/gdisp/ILI9225 \
uGFX/drivers/gdisp/ILI9320 \
uGFX/drivers/gdisp/ILI9325 \
uGFX/drivers/gdisp/ILI9341 \
uGFX/drivers/gdisp/ILI9342 \
uGFX/drivers/gdisp/ILI93xx \
uGFX/drivers/gdisp/ILI9481 \
uGFX/drivers/gdisp/ILI9488 \
uGFX/drivers/gdisp/KS0108 \
uGFX/drivers/gdisp/LGDP4532 \
uGFX/drivers/gdisp/Nokia6610GE12 \
uGFX/drivers/gdisp/Nokia6610GE8 \
uGFX/drivers/gdisp/PCD8544 \
uGFX/drivers/gdisp/PCF8812 \
uGFX/drivers/gdisp/QImage \
uGFX/drivers/gdisp/R61505U \
uGFX/drivers/gdisp/RA6963 \
uGFX/drivers/gdisp/RA8875 \
uGFX/drivers/gdisp/S6D1121 \
uGFX/drivers/gdisp/SPFD54124B \
uGFX/drivers/gdisp/SSD1289 \
uGFX/drivers/gdisp/SSD1306 \
uGFX/drivers/gdisp/SSD1322 \
uGFX/drivers/gdisp/SSD1331 \
uGFX/drivers/gdisp/SSD1351 \
uGFX/drivers/gdisp/SSD1848 \
uGFX/drivers/gdisp/SSD1963 \
uGFX/drivers/gdisp/SSD2119 \
uGFX/drivers/gdisp/ST7565 \
uGFX/drivers/gdisp/ST7735 \
uGFX/drivers/gdisp/STM32LTDC \
uGFX/drivers/gdisp/TLS8204 \
uGFX/drivers/gdisp/TestStub \
uGFX/drivers/gdisp/UC1601s \
uGFX/drivers/gdisp/UC1610 \
uGFX/drivers/gdisp/UC8173 \
uGFX/drivers/gdisp/framebuffer \
uGFX/drivers/ginput/dial/GADC \
uGFX/drivers/ginput/toggle/Pal \
uGFX/drivers/ginput/touch/ADS7843 \
uGFX/drivers/ginput/touch/EXC7200 \
uGFX/drivers/ginput/touch/FT5336 \
uGFX/drivers/ginput/touch/FT5x06 \
uGFX/drivers/ginput/touch/FT6x06 \
uGFX/drivers/ginput/touch/Linux-Event \
uGFX/drivers/ginput/touch/MAX11802 \
uGFX/drivers/ginput/touch/MCU \
uGFX/drivers/ginput/touch/QWidget/example \
uGFX/drivers/ginput/touch/QWidget \
uGFX/drivers/ginput/touch/STMPE610 \
uGFX/drivers/ginput/touch/STMPE811 \
uGFX/drivers/multiple/SDL \
uGFX/drivers/multiple/Win32 \
uGFX/drivers/multiple/X \
uGFX/drivers/multiple/uGFXnet \
uGFX/drivers/multiple/uGFXnetESP8266 \
uGFX/src/gadc \
uGFX/src/gaudio \
uGFX/src/gdisp/fonts \
uGFX/src/gdisp \
uGFX/src/gdisp/mcufont \
uGFX/src/gdriver \
uGFX/src/gevent \
uGFX/src/gfile \
uGFX/src \
uGFX/src/ginput \
uGFX/src/gmisc \
uGFX/src/gos \
uGFX/src/gqueue \
uGFX/src/gtimer \
uGFX/src/gtrans \
uGFX/src/gwin \
uGFX/tools/file2c/binaries/windows \
uGFX/tools/file2c/src \
uGFX/tools/mcufontencoder/binaries/windows \
uGFX/tools/mcufontencoder/src \

